language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -c development.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - jesse.stippel@operun.de
