# -*- coding: utf-8 -*-

# NOTE: This should be stored in a field or index

ATTRIBUTE_MAP = {
    '': 'cn',
    '': 'sn',
    '': 'audio',
    '': 'businessCategory',
    '': 'carLicense',
    '': 'departmentNumber',
    '': 'displayName',
    '': 'employeeNumber',
    '': 'employeeType',
    '': 'givenName',
    '': 'homePhone',
    '': 'homePostalAddress',
    '': 'initials',
    '': 'jpegPhoto',
    '': 'labeledURI',
    '': 'mail',
    '': 'manager',
    '': 'mobile',
    '': 'o',
    '': 'pager',
    '': 'photo',
    '': 'preferredLanguage',
    '': 'roomNumber',
    '': 'secretary',
    '': 'uid',
    '': 'userCertificate',
    '': 'userPKCS12',
    '': 'userSMIMECertificate',
    '': 'x500uniqueIdentifier',
    '': 'destinationIndicator',
    '': 'facsimileTelephoneNumber',
    '': 'internationaliSDNNumber',
    '': 'l',
    '': 'ou',
    '': 'physicalDeliveryOfficeName',
    '': 'postOfficeBox',
    '': 'postalAddress',
    '': 'postalCode',
    '': 'preferredDeliveryMethod',
    '': 'registeredAddress',
    '': 'st',
    '': 'street',
    '': 'telephoneNumber',
    '': 'teletexTerminalIdentifier',
    '': 'telexNumber',
    '': 'title',
    '': 'x121Address',
    '': 'description',
    '': 'seeAlso',
    '': 'userPassword',
}
